### PR TITLE
Don't create SSL dir since it's created in tequila-nginx

### LINKED ISSUE #4: ssl_dir gets changed on every deploy
`ssl_dir` is set to mode 700 (project_user/project_user) in this module and then set to 644 (root/www-data) in tequila-nginx, so it gets changed twice on every deploy.

I'd vote for removing the task from this module and leaving it to be managed by tequila-nginx.

If that sounds OK, I can create a PR.

### PR DESCRIPTION
**Pull request by vkurup**
Closes #4

### CODE REVIEW

**Comment by jbradberry** [comment]
The `ssl_dir` variable should also be removed from defaults/main.yml and README.rst, since it is no longer used in this role.

**Comment by vkurup** [comment]
Thanks @jbradberry for catching those! Updated.

**Comment by jbradberry** [comment]
:+1:

**Comment by jbradberry** [comment]
Yep, good idea to add the CHANGES.rst file.  :rocket:

**Pull request merged**
